Add scopes
accentor/api-client-js pull request #5
Opened 2021-07-13 19:26 UTC by robbevp

Fix #3 
Add the same scopes as accentor/web#413

Instead of setting the initial scope as a class field, I've added them in the constructor. This should not make any functional difference, but the class fields syntax is newer and not yet support by the default eslint parser.

I've also changed the export of `createApiClient` from a default export to a named export. It makes more sense to import everything as `import { createApiSync, AlbumsScope, ... } from ...` instead of import createApiSync { AlbumsScope, ... } from ...`. (This is also easier to build to CJS)

2021-07-14 09:28 UTC, chvp requested changes
This isn't well-typed. Every `index` method can take any `Scope` class if you look at the generated `index` methods. I don't have an immediate suggestion on how to fix it, but I do think it should be fixed.

2021-07-14 09:28 UTC, chvp commented on README.md
> +const generator = api.tracks.indexGenerator(auth, scope?);
The `?` is weird here, if this is a code example.

2021-07-17 09:12 UTC, robbevp commented
> This isn't well-typed. Every `index` method can take any `Scope` class if you look at the generated `index` methods. I don't have an immediate suggestion on how to fix it, but I do think it should be fixed.

I've updated this, so that we can distinguish between indexes with scopes and without. I had to introduce Babel's eslint-parser to use private fields. Browser support is still limited for this, but esbuild can transform this for us during build

2021-07-17 09:22 UTC, chvp reviewed
Hmm, it's still not clear from the API that (for example) the tracks index method only takes a TrackScope.

2021-07-17 09:42 UTC, robbevp commented
> Hmm, it's still not clear from the API that (for example) the tracks index method only takes a TrackScope.

I don't think this is that much of an issue. IMHO its the responsibility of the developer to use this correctly. Someone can also pass a string or an object to a scope that expects an ID, or pass the id from another type of object 🤷 
If we switch to typescript, we can provide some more guidance (even in JS projects)

2021-07-17 20:25 UTC, chvp approved these changes

2021-07-17 20:25 UTC, merged